## Building a hexa GPT



In [2]:
import re
import requests

def get_raw_links(github_url):
    # 获取GitHub页面的内容
    response = requests.get(github_url)

    # 从页面内容中提取出文件名
    file_names = re.findall(r'href="/.*?\.md"', response.text)
    file_names = [fn[6:-1] for fn in file_names]

    # 获取每个文件的raw格式链接
    raw_links = []
    for file_name in file_names:
        file_name = file_name.replace("/blob", "")
        raw_link = f"https://raw.githubusercontent.com/{file_name}"
        raw_links.append(raw_link)

    # 返回所有的raw格式链接
    return raw_links

ans_links = get_raw_links('https://github.com/itrewub/jh-notes/tree/main/All')
print(ans_links[:2])

['https://raw.githubusercontent.com//itrewub/jh-notes/main/All/10%E5%B2%81%E7%94%B7%E5%AD%A9%E7%BB%8F%E5%B8%B8%E6%83%85%E7%BB%AA%E5%A4%B1%E6%8E%A7%E6%98%AF%E5%8F%97%E7%88%B8%E7%88%B8%E8%84%BE%E6%B0%94%E7%9A%84%E5%BD%B1%E5%93%8D%E8%BF%98%E6%98%AF%E7%8E%AF%E5%A2%83%E5%BD%B1%E5%93%8D%E5%AF%BC%E8%87%B4%E7%9A%84%E5%BA%94%E8%AF%A5%E5%A6%82%E4%BD%95%E6%AD%A3%E7%A1%AE%E5%9C%B0%E5%BC%95%E5%AF%BC-x10958066763y1043771095.md', 'https://raw.githubusercontent.com//itrewub/jh-notes/main/All/12-%E6%97%A5%E8%B4%B5%E5%B7%9E%E5%AE%89%E9%A1%BA%E5%A4%A7%E5%B7%B4%E8%BD%A6%E5%9D%A0%E6%B9%96%E4%BA%8B%E4%BB%B6%E9%80%9A%E6%8A%A5%E7%B3%BB%E5%8F%B8%E6%9C%BA%E5%9B%A0%E5%AF%B9%E6%8B%86%E8%BF%81%E4%B8%8D%E6%BB%A1%E8%93%84%E6%84%8F%E6%8A%A5%E5%A4%8D%E7%A4%BE%E4%BC%9A%E8%BF%98%E6%9C%89%E5%93%AA%E4%BA%9B%E6%96%B0%E7%9A%84%E4%BF%A1%E6%81%AF%E9%87%8F-x10621254739y1011320797.md']


In [3]:
#print(ans_links)
#https://raw.githubusercontent.com/itrewub/jh-notes/main/All/12-%E6%97%A5%E8%B4%B5%E5%B7%9E%E5%AE%89%E9%A1%BA%E5%A4%A7%E5%B7%B4%E8%BD%A6%E5%9D%A0%E6%B9%96%E4%BA%8B%E4%BB%B6%E9%80%9A%E6%8A%A5%E7%B3%BB%E5%8F%B8%E6%9C%BA%E5%9B%A0%E5%AF%B9%E6%8B%86%E8%BF%81%E4%B8%8D%E6%BB%A1%E8%93%84%E6%84%8F%E6%8A%A5%E5%A4%8D%E7%A4%BE%E4%BC%9A%E8%BF%98%E6%9C%89%E5%93%AA%E4%BA%9B%E6%96%B0%E7%9A%84%E4%BF%A1%E6%81%AF%E9%87%8F-x10621254739y1011320797.md

In [6]:
import requests
import markdown
from bs4 import BeautifulSoup
def get_text(url):
  response = requests.get(url)
  md_content = response.text

  html_content = markdown.markdown(md_content)
  soup = BeautifulSoup(html_content, 'html.parser')
  # 获取纯文本内容
  str_content = soup.get_text()
  return str_content

print(get_text(ans_links[0]))
ans = [get_text(url) for url in ans_links]

10岁男孩经常情绪失控，是受爸爸脾气的影响还是环境影响导致的？应该如何正确地引导？
Tags: Clan

10岁男孩经常情绪失控，是受爸爸脾气的影响还是环境影响导致的？应该如何正确地引导？

让我们来梳理一下你的问题。
首先，儿子的表现令你感到忧虑和失望，这导致了痛苦。
为这个痛苦，你希望定位原因。
你定位原因的时候遇到了这样一种纠结——如果定位在自己身上，不知道该怎么总结自己哪里有错。某种程度上说，你现在其实已经尽了全力了——有哪位父母不是已经尽了全力了呢？所以，就算定位在自己身上，也无余力可用了，定位在自己身上又有何意义呢？
而无论是定位在父亲身上、祖父母身上、还是环境身上，都一样沉重。定位到ta们身上，要怎么改变ta们呢？离婚吗？还是威逼利诱、说服谈判要ta们改变呢？难道现在不也已经是尽了全力管控了这些你觉得有害的因素，实在只能管控到这个程度，没有办法了吗？
其实，你真正的困境并不是看到有各种有害的因素存在，没有办法去解决，而是就算有办法，你担忧没有力气解决。
其实，没有力气为子女争取自己理想中最低限度的生活了，这种绝望感，才是真正的问题。
你累了，这才是真正的问题。
你现在处在想要问到一个好的办法，然后逼着自己再挤出一份力量来再搏一搏的状态。
你跟子女讲话，看似心平气和，温言细语，但其实是竭尽全力的控制着才压住的，不是吗？
你不希望自己的焦虑影响到子女，想要ta们不要平添这份负担，所以在控制着，不是吗？
光是这份克制，已经让人精疲力竭了，不是吗？
在这份重压之下，再给你更多的妙计，其实对你是没什么用的。因为你其实没有力气再负担更多了。勉强扛更多的责任，你也很快会无以为继。因为无以为继，这个新的拯救计划坦白说不太可能被有效实施，而半途而废的努力，只会让你陷入更深的忧虑。
这个恶性循环迟早要教会你一件事——此路不通。
你必须有某种方法，先把心头的重担卸下。先让自己有心力可以拿来做改善才行。不先卸掉这副担子，任何妙计都没有燃料，也难有好结果。
而更进一步的，真的把这担子卸掉了，你的精气神直接就会有一些良性的改变。同样的话，用不同的精神状态去说，效力是截然不同的。有很大的概率，那个卸下了重担的你，没有改变任何原有的策略和节奏，就已经把事情引向了别的方向。
而这个千斤重担是什么呢？
就是“把子女‘不正常’的人生轨迹趋势，看作一件绝对要想办法避免的坏事，并且把避免不了

In [7]:
print(ans[10])

34 岁华裔工程师在美国遭抢笔记本电脑，追击歹徒被拖行后身亡，为什么会发生此类事件？是个案吗？
Tags: Society, Clan

34 岁华裔工程师在美国遭抢笔记本电脑，追击歹徒被拖行后身亡，为什么会发生此类事件？是个案吗？

美国是一个高度依赖自卫来保证安全的国家，不能沿用在东亚社会里养成的安全观。
美国人对人的生命安全看得其实不重，并不像中国有一种“人命大过天”的观念。
在美国，人们重视的是基于契约而产生的责任。他们并不是重视人命本身，而是重视常常因此而来的天价赔偿责任。
身在美国，你要顺着契约链条一路追踪下去，会发现你经常处在一种没有任何人要为你的某种死亡负责的状态。
这类问题，他们往往用自购保险加免责条款的方式处理了。先用免责条款请你自担风险，然后建议你购买保险以防万一。
就这样了。
如果要服务方为你的安全负责，那么这项服务一定是天价——坦白说就是把他要买的保险拆成你的一人份然后翻了几倍强制打包在服务费里卖给你了罢了。
而即便如此，服务方仍然是受到有限责任公司制度保护的。说不定向你提供服务的企业根本就没有购买保险，就是打算一旦出事就破产了事罢了。
这样的好处是，美国人做起生意来胆子很大——因为各种风险都有一个可以预见的保底。哪怕闹出人命也有一个确切的数字——甚至这个数字未必很高。
坏处是美国在本质上就不安全，需要的安全意识、安全技能、安全投入都很大。


In [ ]:
# let's look at the first 1000 characters
print(len(ans_links))

1000


In [7]:
#!pip install jieba
import jieba
chars = set()

for lst in ans:
    
    for item in lst:
        words = jieba.cut(item)
        
        for word in words:
           # print(word)
            chars.add(word)
vocab_size = len(chars)
print(vocab_size)

Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\zhang\AppData\Local\Temp\jieba.cache
Loading model cost 0.540 seconds.
Prefix dict has been built successfully.


4179


In [8]:
for i in chars:
    if len(i) > 1:
        print(i)

In [12]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("我爱你"))
print(decode(encode("我爱你")))

[1310, 90, 2318]
我爱你


In [13]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = [torch.tensor(encode(text), dtype=torch.long) for text in ans]
print(data[0][:1000]) # the 1000 characters we looked at earier will to the GPT look like this

tensor([2380, 4075, 4081, 1668, 3449,  219,  406, 2943, 4037, 1382,  104,  469,
        3647, 1092, 2326, 2326, 4032, 1434, 3472, 2855, 1844, 1661, 3647,  228,
         750, 2855, 1844,  451,  471, 3472, 3466, 2144, 2721, 4003, 1946, 1662,
        1298,  312, 2833,  451, 3466,  224, 1951, 3614,  138, 3698, 1608, 1205,
        3300, 2640, 3614, 2702,  224,  224, 2380, 4075, 4081, 1668, 3449,  219,
         406, 2943, 4037, 1382,  104,  469, 3647, 1092, 2326, 2326, 4032, 1434,
        3472, 2855, 1844, 1661, 3647,  228,  750, 2855, 1844,  451,  471, 3472,
        3466, 2144, 2721, 4003, 1946, 1662, 1298,  312, 2833,  451, 3466,  224,
         224, 2530, 1310, 1346, 3679,  233, 1544,  388, 3165, 2318, 3472, 2357,
        2200, 2676,  224, 1113, 3088,  469, 3924, 3134, 3472, 3927,  342, 3390,
        2318, 2228,  487, 1377, 3151, 3980, 1382, 3576,  469, 2145,  451,  471,
        2927, 1293, 4061, 2676,  224,  913, 2145, 3495, 1293, 4061,  469, 2318,
        3439, 3576, 3462, 1401, 1726, 27

In [14]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [ ]:
block_size = 10
decode(train_data[0][:block_size+1].tolist())

In [ ]:
# x = train_data[:block_size]
# y = train_data[1:block_size+1]
# for t in range(block_size):
#     context = x[:t+1]
#     target = y[t]
#     print(f"when input is {context} the target: {target}")

In [35]:
torch.manual_seed(9907)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size =12 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data_list = train_data if split == 'train' else val_data
    X, Y = [], []
    for data in data_list:
      # avoid too short answer
      if len(data) <= block_size:continue
      ix = torch.randint(len(data) - block_size, (batch_size,))
      x = torch.stack([data[i:i+block_size] for i in ix])
      y = torch.stack([data[i+1:i+block_size+1] for i in ix])
      X.append(x)
      Y.append(y)
    return torch.cat(X, dim=0).to('cuda'), torch.cat(Y, dim=0).to('cuda')

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {decode(context.tolist())} the target: {target}")

inputs:
torch.Size([3600, 12])
tensor([[3472, 3747, 1092,  ..., 3647,  388, 2953],
        [ 622,  913, 2927,  ..., 1108,  469, 2318],
        [2530, 1442, 1345,  ..., 3647, 1095, 3466],
        ...,
        [3048,  205, 3472,  ..., 2224,  469, 2318],
        [1946, 1144, 2145,  ..., 3848, 2397, 2045],
        [1711,  913, 2247,  ..., 2676,  224, 2318]], device='cuda:0')
targets:
torch.Size([3600, 12])
tensor([[3747, 1092, 1945,  ...,  388, 2953, 3197],
        [ 913, 2927, 3078,  ...,  469, 2318, 1346],
        [1442, 1345, 2390,  ..., 1095, 3466,  224],
        ...,
        [ 205, 3472, 2888,  ...,  469, 2318, 2247],
        [1144, 2145,  402,  ..., 2397, 2045, 3856],
        [ 913, 2247, 2499,  ...,  224, 2318, 4003]], device='cuda:0')
----
when input is 的 the target: 3747
when input is 的接 the target: 1092
when input is 的接受 the target: 1945
when input is 的接受它 the target: 469
when input is 的接受它， the target: 555
when input is 的接受它，相 the target: 1349
when input is 的接受它，相信 the target: 1

In [17]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(len(chars))
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))
print((m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

torch.Size([43200, 4179])
tensor(8.8286, grad_fn=<NllLossBackward0>)
闻娄侠驿亩盖灼骊技辩勤遇典愤疵轮诸彈陵跨咂鼻掖摧谋慰辍睹猿君勝庇雪奥发矫辘．记烧焖吵纪锤拽召鹊签荒朴》放扎眩箪仑幼陀嘛迫骤谜诠契易槜致踩篆制郡山揖在封深D敞特蜡此阿滚佰墩盗娄亲忑阿铃蝇掀栈狭毫螨晦踪蜡责
[0, 2996, 1276, 1933, 469, 1954, 2308, 2513, 3571, 484, 3843, 25, 3332, 3215, 4004, 2466, 1229, 2073, 2347, 3192, 1770, 276, 265, 3511, 1362, 1293, 414, 1239, 1741, 3612, 3892, 2022, 3921, 173, 706, 3891, 314, 599, 3903, 3135, 1944, 1998, 713, 253, 1028, 899, 746, 2231, 1633, 929, 1233, 3686, 2564, 3479, 2330, 3229, 91, 3848, 2830, 2307, 2792, 2738, 2581, 2198, 3533, 578, 3216, 4000, 4053, 1140, 1569, 2547, 2911, 2503, 2579, 3535, 877, 1549, 3938, 2582, 318, 4000, 1533, 1902, 1244, 4104, 258, 3694, 2403, 2103, 3231, 4061, 1809, 2681, 2535, 2665, 1558, 3813, 1040, 4105, 1687]


In [18]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [26]:
for i in range(len(train_data)):
    torch.save(train_data[i].to(torch.device('cpu')), str(i)+'train.pth')
for i in range(len(val_data)):
    torch.save(val_data[i].to(torch.device('cpu')), str(i)+ 'val.pth')

# y = torch.load('0train.pth')
# torch.equal(y, train_data[0])

True

In [2]:
#import torch
train_data = [torch.load(str(i)+'train.pth') for i in range(900)]
val_data = [torch.load(str(i)+'train.pth') for i in range(100)]

In [90]:
# verify
# for i in range(900):
#     if not torch.equal(train_data[i],train_data2[i]):
#         print(i)

In [21]:
import time
s_t = time.time()
batch_size = 50
for step in range(50): # increase number of steps for good results... 
    
    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()
    
    if step % 10 == 0:
        print(time.time()-s_t)

print(loss.item())


248.2430076599121
2419.103317260742
4604.466238021851
6763.673887252808
8915.599104642868
8.746464729309082


In [78]:
#print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))

In [9]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import time
# hyperparameters
batch_size = 8 # how many independent sequences will we process in parallel?
block_size = 10 # what is the maximum context length for predictions?
max_iters = 2500
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
eval_iters = 100
n_embd = 32
n_head = 4
n_layer = 1
dropout = 0.0
vocab_size = 4179
# ------------

torch.manual_seed(9907)
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data_list = train_data if split == 'train' else val_data
    X, Y = [], []
    for data in data_list:
      # avoid too short answer
      if len(data) <= block_size:continue
      ix = torch.randint(len(data) - block_size, (batch_size,))
      x = torch.stack([data[i:i+block_size] for i in ix])
      y = torch.stack([data[i+1:i+block_size+1] for i in ix])
      X.append(x)
      Y.append(y)
    return torch.cat(X, dim=0).to('cuda'), torch.cat(Y, dim=0).to('cuda')

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)
#love_context = torch.tensor(encode('我爱你'), dtype=torch.long).to(device)
st = time.time()

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}, time {time.time()-st}")
        #print(decode(m.generate(love_context, max_new_tokens=50)[0].tolist()))
    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))

cuda
0.284627 M parameters
step 0: train loss 8.5094, val loss 8.5158, time 40.53957009315491


OutOfMemoryError: CUDA out of memory. Tried to allocate 1.12 GiB (GPU 0; 6.00 GiB total capacity; 3.51 GiB already allocated; 0 bytes free; 4.64 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

In [3]:

torch.cuda.max_memory_allocated('cuda')

0

## The mathematical trick in self-attention

In [ ]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [ ]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [ ]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [ ]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

True

In [ ]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


True

In [ ]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [ ]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [ ]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [ ]:
k.var()

tensor(1.0449)

In [ ]:
q.var()

tensor(1.0700)

In [ ]:
wei.var()

tensor(1.0918)

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [ ]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [ ]:
class LayerNorm1d: # (used to be BatchNorm1d)
  
  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)
  
  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out
  
  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [ ]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [ ]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [ ]:
# French to English translation example:

# <--------- ENCODE ------------------><--------------- DECODE ----------------->
# les réseaux de neurones sont géniaux! <START> neural networks are awesome!<END>



### Full finished code, for reference

You may want to refer directly to the git repo instead though.

In [ ]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


0.209729 M parameters
step 0: train loss 4.4116, val loss 4.4022
step 100: train loss 2.6568, val loss 2.6670
step 200: train loss 2.5090, val loss 2.5058
step 300: train loss 2.4198, val loss 2.4340
step 400: train loss 2.3503, val loss 2.3567
step 500: train loss 2.2970, val loss 2.3136
step 600: train loss 2.2410, val loss 2.2506
step 700: train loss 2.2062, val loss 2.2198
step 800: train loss 2.1638, val loss 2.1871
step 900: train loss 2.1232, val loss 2.1494
step 1000: train loss 2.1020, val loss 2.1293
step 1100: train loss 2.0704, val loss 2.1196
step 1200: train loss 2.0382, val loss 2.0798
step 1300: train loss 2.0249, val loss 2.0640
step 1400: train loss 1.9922, val loss 2.0354
step 1500: train loss 1.9707, val loss 2.0308
step 1600: train loss 1.9614, val loss 2.0474
step 1700: train loss 1.9393, val loss 2.0130
step 1800: train loss 1.9070, val loss 1.9943
step 1900: train loss 1.9057, val loss 1.9871
step 2000: train loss 1.8834, val loss 1.9954
step 2100: train loss 1.